version: '3.8'

services:
  create3-sim-humble:
    build:
      context: .
      dockerfile: Dockerfile
    image: create3-sim-humble:latest
    container_name: create3_sim_humble
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - ${HOME}/ros2_ws:/root/ros2_ws
      - ${XAUTHORITY}:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint: ["/ros_entrypoint.sh"]
    command: ["bash"]