version: '3.8'

services:
  ros-jazzy-cyclone:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros-jazzy-cyclone:latest
    container_name: ros_jazzy_cyclone
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - ${HOME}/ros2_ws:/root/ros2_ws
      - ${XAUTHORITY}:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint: ["/ros_entrypoint.sh"]
    command: ["bash"]